### ISSUE TITLE
mermaid version error (version 0.0.8)

### ISSUE THREAD

**Issue by shayansm2** [nhannht/obsidian-smart-gantt#1]
I get this error when trying to use the gantt chart version 0.0.8

```
Syntax error in text
mermaid version 10.9.0
```

**Comment by nhannht** [comment]
Sorry for late reply.

It is really hard for me to grasp the context. What is your input, where and when that error occurred.
Can you give me some screenshots/ or copy-paste the stack trace of what happened.

**Comment by nhannht** [comment]
done!
