### ISSUE TITLE
Gantt code block stopped working

### ISSUE THREAD

**Issue by mantans** [nhannht/obsidian-smart-gantt#13]
@nhannht Thank you for this awesome plugin!

Since the latest update i noticed that code block don't render the gantt graph inside my daily note, despite this in the side-bar everything works like a charm:

![Screenshot 2024-06-29 at 21 52 55](https://github.com/nhannht/obsidian-smart-gantt/assets/39434528/5bbeaa71-fb39-4915-8671-caffeda68251)

**Comment by nhannht** [comment]
Sorry, I intentional turn it off due to the branch in the logic need to be rewritten.

**Comment by mantans** [comment]
Hi @nhannht no problem at all, thank you for the clarification.

**Comment by nhannht** [comment]
- [ ] Update README.md

**Comment by nhannht** [comment]
Done in ![this commit](https://github.com/nhannht/obsidian-smart-gantt/commit/be37569ad1b53fc58f67c99f8b4c33ba7c7f6096)

Now you can plot as normal.
And you can try right click/ hold (on mobile) in the plot to config things

**Comment by mantans** [comment]
Great addition! thanks a lot
