### ISSUE TITLE
Tasks  identification problem

### ISSUE THREAD

**Issue by Litt7e** [nhannht/obsidian-smart-gantt#3]
It seems that every tasks in my valut will be considered necessary to be drawn in a Gantt chart, but I only need tasks in current file to be plotted
![image](https://github.com/nhannht/obsidian-smart-gantt/assets/44261353/cbea2b11-148f-4fd8-8cca-5bda9d3627c8)
![image](https://github.com/nhannht/obsidian-smart-gantt/assets/44261353/b543ea76-6c1f-4e75-bdd4-5d2dd283b773)

**Comment by nhannht** [comment]
done!

![image](https://github.com/nhannht/obsidian-smart-gantt/assets/69144096/e3da7cc9-c04f-470f-b23b-5045363e9dc8)
