### ISSUE TITLE
[possible bug]: Maximum text size in diagram exceeded

### ISSUE THREAD

**Issue by DaisukeMiyazaki** [nhannht/obsidian-smart-gantt#6]
@nhannht Thank you for this awesome plugin!

My checkboxes (tasks) contain more than 50 characters per line and the attached error showed up. This resulted in failing on rendering the gantt chart. 

I know this is my data incompatibility and should keep them all shorter, but I'd appreciate it if the plugin can trim the letters like 
"ThisIsAnExampleTaskTh....." etc. 

<img width="678" alt="スクリーンショット 2024-06-17 17 02 43" src="https://github.com/nhannht/obsidian-smart-gantt/assets/47438000/d14228ee-492b-41ed-8ad6-b6ded2cd3089">

**Comment by DaisukeMiyazaki** [comment]
Or potentially, this might be caused by the fact that my tasks (including done and not done) have over 3500 checkboxes in the vault, and exceeding the limit of the mermaid.

https://github.com/mermaid-js/mermaid-cli/issues/113

**Comment by nhannht** [comment]
Thank you for doing research, it helps me reduce the time to fix. I just add in the new version
```typescript
mermaid.initialize({
	startOnLoad: true,
	maxTextSize:99999999,
				})
```

Can you try it and report to me if the hotfixs worked?

I will write some scripts to generate very big size samples and test this case. But at the minimum time, I need at least tomorrow to have a new patch.

**Comment by DaisukeMiyazaki** [comment]
@nhannht Thank you for your quick response on this! Seems like I've faced another issue here. I forked this repository and changed the `maxTextSize: 500000` as well but still the same error occurs...

<img width="393" alt="スクリーンショット 2024-06-17 22 27 38" src="https://github.com/nhannht/obsidian-smart-gantt/assets/47438000/34da18c5-d82a-41b4-a85c-e896de6e8889">

**Comment by DaisukeMiyazaki** [comment]
I'm going to add the console error here as well. Some kind of parsing might be failing when converting the checkboxes to HTML? on rendering.
<img width="526" alt="スクリーンショット 2024-06-17 22 41 03" src="https://github.com/nhannht/obsidian-smart-gantt/assets/47438000/b9052d47-8953-48f2-9891-634a4e7c755c">

**Comment by nhannht** [comment]
Haizz, seriously, if I don't have the same sample from your case (actually it means your private data).

 It is hard for me just to guess what happened. We know there must be some task which produced the bug. 
But we have thousands of tasks in your vault and impossible for us to guess which is the cause. 

Now, I suggest a simple solution. Please only use the "Current file" filter.  Well, there will be a change we can narrow down which file has the task that caused the error. You don't need to report me now. Just use the plugin like it was limited in feature until you find the file that causing the error. After that, if you don't mind, please show me all the tasks in that file. (change the sensitive info if needed).

**Comment by nhannht** [comment]
> @nhannht Thank you for your quick response on this! Seems like I've faced another issue here. I forked this repository and changed the `maxTextSize: 500000` as well but still the same error occurs...
> 
> <img alt="スクリーンショット 2024-06-17 22 27 38" width="393" src="https://private-user-images.githubusercontent.com/47438000/340321648-34da18c5-d82a-41b4-a85c-e896de6e8889.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MzQ4NTIsIm5iZiI6MTcxODYzNDU1MiwicGF0aCI6Ii80NzQzODAwMC8zNDAzMjE2NDgtMzRkYTE4YzUtZDgyYS00MWI0LWE4NWMtZTg5NmRlNmU4ODg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDE0MjkxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4Y2U1MzJjMWMzOGI4YmRkYmQyODRkMDdmNzAwMDQzMmVjYTllNjY5NGU4Y2RkZTdhYTk4NmYyNDYyMGQxMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.waA1aqI8vUwxAIkLu8JmMF6_nmlgZEMnxb5WqHRznGU">

And about this report, I want to make sure about the phrase "same error". Are you sure it is the same error as the above error, I don't see the sentence  "Maximum text size in diagram exceeded"

**Comment by nhannht** [comment]
done, break up with Mermaidjs and move to gantt-task-react, it 's time to get new boyfriend
