### ISSUE TITLE
Display Syntax error in text

### ISSUE THREAD

**Issue by qihaogithub** [nhannht/obsidian-smart-gantt#8]
![image](https://github.com/nhannht/obsidian-smart-gantt/assets/51152162/541744e4-186c-4ca6-9f37-985a398e1488)

**Comment by nhannht** [comment]
Maybe related with #7  and #2

**Comment by nhannht** [comment]
oh, I think I just tinker this plugin a bit, maybe it will be better with this issues. Can you check it?.

**Comment by nhannht** [comment]
Oh, I just tested with your example, it works, right?. It is not perfect, it was parsed at 3 different times. I will keep improving it. But at least it will not give bug in plot anymore



![Image](https://github.com/nhannht/obsidian-smart-gantt/assets/69144096/e7d83a68-c5c7-4cfe-996b-06e00b5b1aea)

**Comment by nhannht** [comment]
done, i am not using mermaidjs anymore.
